### ISSUE TITLE
unsubscribetopic does not remove the topic from the consumer _topics array

### ISSUE THREAD

**Issue by ChandrasekharPo-Kore** [marcuswestin/node-kafka#10]
Calling unsubscribeTopic on consumer is not removing it from _topics array owing to the filter criteria.
If modified it to !== it works fine.

this.unsubscribeTopic = function(name) {
        this._topics = this._topics.filter(function(x) { return x.name == name })  
        if (this._topics.length == 0) this._unschedulePoll()
        return this
}

This is creating a problem.Consumer 'message' event is getting triggered indefinitely.

thank you for the wonderful contribution.

**Comment by marcuswestin** [comment]
Sweet, thanks! Please make the change and send a pull request - I'll happily pull it in. Cheers!

-- while mobile

**Comment by ChandrasekharPo-Kore** [comment]
Fix merged
