### ISSUE TITLE
npm needs updating

### ISSUE THREAD

**Issue by klucar** [marcuswestin/node-kafka#4]
When I installed via npm, the version it pulled down didn't have Consumer.subscribeTopic(....) function.  Worked as advertised when I cloned from github, and did an npm link though.

**Comment by marcuswestin** [comment]
Thanks! Done and done. http://search.npmjs.org/#/kafka

**Comment by marcuswestin** [comment]
fyi: additional issues fixed by @phillips in https://github.com/marcuswestin/node-kafka/pull/5 and https://github.com/marcuswestin/node-kafka/pull/6. Cheers!
